name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  SKIP_ENV_VALIDATION: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint
